services:
  postgres:
    image: postgres:16
    container_name: techtest-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tech_test
    ports:
      - "5432:5432"
    volumes:
      - pgdata_techtest:/var/lib/postgresql/data

volumes:
  pgdata_techtest: